[package]
name = "mithril"
version = "0.9.0"
authors = ["Michael Bohn <spaceodyssey@gmx.de>"]

[lib]
name = "mithril"

[dependencies]
groestl = "0.7.0"
blake = "2.0.0"
jh-ffi = "0.0.2"
skein-ffi = "0.0.1"
serde = "1.0.77"
serde_json = "1.0.27"
serde_derive = "1.0.77"
config = "0.9.0"
log = "0.4.5"
env_logger = "0.5.13"
num_cpus = "1.8.0"
bandit = "0.12.0"
byteorder = "1.2.6"
tiny-keccak = "1.4.2"
dirs = "1.0.3"
