[package]
name = "mithril"
version = "0.8.0"
authors = ["Michael Bohn <spaceodyssey@gmx.de>"]

[lib]
name = "mithril"

[dependencies]
groestl = "0.3.0"
blake = "2.0.0"
jh-ffi = "0.0.2"
skein-ffi = "0.0.1"
serde = "1.0.41"
serde_json = "1.0.15"
serde_derive = "1.0.41"
config = "0.8.0"
log = "0.4.1"
env_logger = "0.5.9"
num_cpus = "1.0"
bandit = "0.11.1"
byteorder = "1.2.2"
