[package]
name = "mithril"
version = "0.1.0"
authors = ["Michael Bohn <spaceodyssey@gmx.de>"]

[lib]
name = "mithril"

[dependencies]
aesti = "0.3.0"
groestl = "0.3.0"
blake = "2.0.0"
jh-ffi = "0.0.2"
skein-ffi = "0.0.1"
serde = "1.0.15"
serde_json = "1.0.3"
serde_derive = "1.0.15"
config = "0.7.0"
