[package]
name = "mithril"
version = "0.9.0"
authors = ["Michael Bohn <spaceodyssey@gmx.de>"]

[lib]
name = "mithril"

[dependencies]
groestl = "0.8.0"
blake = "2.0.0"
jh-ffi = "0.5.0"
skein-ffi = "0.5.0"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.77"
config = "0.9.1"
log = "0.4.6"
env_logger = "0.5.13"
num_cpus = "1.8.0"
bandit = "0.12.0"
byteorder = "1.2.7"
tiny-keccak = "1.4.2"
dirs = "1.0.4"
