
[pool]
pool_address = "iron-pool.com:5555"
wallet_address = ""
pool_password = ""

[worker]
num_threads = 8

[metric]
enabled = false
resolution = 100 #determines how often a hash result is reported
sample_interval_seconds = 60
report_file = "/path/to/hash/report/file.csv"

[hardware]
has_aes = true # disable, if your cpu has no aes-ni support
